version: 2

builds:
  - id: pigeon
    main: ./cmd/pigeon
    binary: pigeon
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
