// Package hub routes incoming messages from platform listeners to connected
// MCP sessions. The daemon creates a single Hub and passes it to listeners.
// MCP shim processes register themselves as sessions when they connect.
package hub

import (
	"context"
	"fmt"
	"log/slog"
	"sync"
)



// Session represents a connected MCP shim process.
type Session struct {
	// SessionID is the pigeon session ID (UUID) generated by `pigeon claude`.
	SessionID string
	// CWD is the working directory of the Claude Code session.
	CWD string
	// Send delivers a message to this session. Provided by the transport
	// layer (e.g. SSE) when the session registers.
	Send func(ctx context.Context, incoming IncomingMsg) error
}

// Hub manages active MCP sessions and routes incoming messages to them.
type Hub struct {
	mu       sync.RWMutex
	sessions map[string]*Session // SessionID → session
}

// New creates an empty Hub.
func New() *Hub {
	return &Hub{
		sessions: make(map[string]*Session),
	}
}

// Register adds a session to the hub. Returns an error if the session ID is already taken.
// TODO: validate session ID and CWD against session files on disk. Reject if the
// session ID is unknown or the CWD doesn't match what's stored in the session file.
func (h *Hub) Register(s *Session) error {
	h.mu.Lock()
	defer h.mu.Unlock()

	if _, exists := h.sessions[s.SessionID]; exists {
		return fmt.Errorf("session %s already registered", s.SessionID)
	}
	h.sessions[s.SessionID] = s
	slog.Info("session registered", "session_id", s.SessionID, "cwd", s.CWD)
	return nil
}

// Unregister removes a session from the hub.
func (h *Hub) Unregister(sessionID string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	if s, exists := h.sessions[sessionID]; exists {
		delete(h.sessions, sessionID)
		slog.Info("session unregistered", "session_id", sessionID, "cwd", s.CWD)
	}
}

// Route delivers an incoming message to the first available session.
// If no session is connected, the message is dropped with a warning.
func (h *Hub) Route(ctx context.Context, incoming IncomingMsg) error {
	h.mu.RLock()
	target := h.pickSession()
	h.mu.RUnlock()

	if target == nil {
		// TODO: start a new Claude Code session and register it, instead of dropping.
		slog.Warn("no session available, dropping message", "incoming", incoming)
		return nil
	}
	return target.Send(ctx, incoming)
}

// Sessions returns the number of active sessions.
func (h *Hub) Sessions() int {
	h.mu.RLock()
	defer h.mu.RUnlock()
	return len(h.sessions)
}

// pickSession returns the first session found. Caller must hold at least a read lock.
func (h *Hub) pickSession() *Session {
	for _, s := range h.sessions {
		return s
	}
	return nil
}
