// Package hub routes incoming messages from platform listeners to connected
// MCP sessions. The daemon creates a single Hub at startup. Listeners call
// Route() when a new message arrives, and the hub delivers it to the
// appropriate Claude Code session via SSE.
package hub

import (
	"context"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/anish/claude-msg-utils/internal/account"
	"github.com/anish/claude-msg-utils/internal/claude"
	"github.com/anish/claude-msg-utils/internal/store"
)

// MessageNotifyFunc is called by listeners when a new message has been
// written to disk.
type MessageNotifyFunc func(acct account.Account, conversation string)

// signalBufferSize is the capacity of each channel's delivery signal buffer.
// If full, new signals are dropped — the goroutine will catch up on its
// next drain since it reads all messages since last_delivered.
const signalBufferSize = 64

// Session represents a connected MCP shim process.
type Session struct {
	// SessionID is the pigeon session ID (UUID) generated by `pigeon claude`.
	SessionID string
	// CWD is the working directory of the Claude Code session.
	CWD string
	// Send delivers a message to this session. Provided by the transport
	// layer (SSE) when the session registers.
	Send func(ctx context.Context, incoming IncomingMsg) error
	// Ready is closed when the SSE event loop starts and the session can
	// receive messages. The hub waits on this before sending the hello.
	Ready chan struct{}
}

// channel is a per-platform+account delivery goroutine.
type channel struct {
	acct      account.Account
	sessionID string
	signal    chan deliverySignal
}

type deliverySignal struct {
	kind         signalKind
	conversation string // only set for signalNewMessage
}

type signalKind int

const (
	signalNewMessage signalKind = iota // a specific conversation has a new message
	signalConnected                    // session just connected — send hello and drain all
)

// Hub manages active MCP sessions and routes incoming messages to them.
type Hub struct {
	mu       sync.RWMutex
	sessions map[string]*Session  // SessionID → connected session
	channels map[string]*channel  // account slug → delivery channel
	ctx      context.Context
	cancel   context.CancelFunc
}

// New creates a Hub, loads session files, starts delivery goroutines, and
// watches for new session files. Returns an error if session files cannot
// be read (no sessions configured yet is not an error). Call Stop() to shut down.
func New(ctx context.Context) (*Hub, error) {
	sessions, err := claude.ListAllSessions()
	if err != nil {
		return nil, fmt.Errorf("load session files: %w", err)
	}

	ctx, cancel := context.WithCancel(ctx)
	h := &Hub{
		sessions: make(map[string]*Session),
		channels: make(map[string]*channel),
		ctx:      ctx,
		cancel:   cancel,
	}

	for _, s := range sessions {
		h.startChannel(s)
	}
	if len(sessions) > 0 {
		slog.Info("hub started with session channels", "count", len(sessions))
	}

	// Watch for new/updated session files and start channels as needed.
	go h.watchSessionFiles(ctx)

	return h, nil
}

// watchSessionFiles watches for changes in the sessions directory and
// starts delivery channels for any new session files.
func (h *Hub) watchSessionFiles(ctx context.Context) {
	for sessions := range claude.WatchSessions(ctx) {
		h.reconcileChannels(sessions)
	}
}

// reconcileChannels starts delivery channels for session files that
// don't have one yet. Does not stop existing channels.
func (h *Hub) reconcileChannels(sessions []*claude.Session) {
	h.mu.RLock()
	existing := make(map[string]bool, len(h.channels))
	for k := range h.channels {
		existing[k] = true
	}
	h.mu.RUnlock()

	for _, s := range sessions {
		acct := account.New(s.Platform, s.Account)
		if existing[acct.String()] {
			continue
		}
		h.startChannel(s)
		slog.Info("new session file detected, delivery channel started",
			"account", acct, "session_id", s.SessionID)
	}
}

// Stop shuts down all delivery goroutines.
func (h *Hub) Stop() {
	h.cancel()
}

// Register adds a connected MCP shim session to the hub. Validates the
// session ID exists in a session file and the CWD matches.
func (h *Hub) Register(s *Session) error {
	// Validate against session files on disk.
	sessions, err := claude.ListAllSessions()
	if err != nil {
		return fmt.Errorf("validate session: %w", err)
	}
	var found *claude.Session
	for _, cs := range sessions {
		if cs.SessionID == s.SessionID {
			found = cs
			break
		}
	}
	if found == nil {
		return &RegistrationError{
			SessionID: s.SessionID,
			Reason:    "no session file found — launch via 'pigeon claude' first",
		}
	}
	if found.CWD != s.CWD {
		return &RegistrationError{
			SessionID: s.SessionID,
			Reason:    "working directory mismatch: session file has " + found.CWD + " but shim reported " + s.CWD,
		}
	}

	h.mu.Lock()
	defer h.mu.Unlock()

	if _, exists := h.sessions[s.SessionID]; exists {
		return &RegistrationError{
			SessionID: s.SessionID,
			Reason:    "session already registered",
		}
	}
	h.sessions[s.SessionID] = s
	slog.Info("session registered", "session_id", s.SessionID, "cwd", s.CWD)

	// Signal the delivery goroutine to send hello and drain pending messages.
	acct := account.New(found.Platform, found.Account)
	if ch, exists := h.channels[acct.String()]; exists {
		select {
		case ch.signal <- deliverySignal{kind: signalConnected}:
			slog.Info("signalled hello + pending drain on connect", "session_id", s.SessionID)
		default:
		}
	}

	return nil
}

// Unregister removes a session from the hub.
func (h *Hub) Unregister(sessionID string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	if s, exists := h.sessions[sessionID]; exists {
		delete(h.sessions, sessionID)
		slog.Info("session unregistered", "session_id", sessionID, "cwd", s.CWD)
	}
}

// Route signals that a new message has arrived for the given account and
// conversation. Non-blocking — returns immediately.
func (h *Hub) Route(acct account.Account, conversation string) {
	key := acct.String()

	h.mu.RLock()
	ch, exists := h.channels[key]
	h.mu.RUnlock()

	if !exists {
		slog.Warn("no session configured, message not routed",
			"account", acct, "conversation", conversation)
		return
	}

	select {
	case ch.signal <- deliverySignal{kind: signalNewMessage, conversation: conversation}:
	default:
		slog.Error("delivery signal buffer full, message delivery may be delayed",
			"account", acct, "conversation", conversation,
			"buffer_size", signalBufferSize)
	}
}

// Sessions returns the number of active (connected) sessions.
func (h *Hub) Sessions() int {
	h.mu.RLock()
	defer h.mu.RUnlock()
	return len(h.sessions)
}

func (h *Hub) startChannel(s *claude.Session) {
	acct := account.New(s.Platform, s.Account)

	ch := &channel{
		acct:      acct,
		sessionID: s.SessionID,
		signal:    make(chan deliverySignal, signalBufferSize),
	}

	h.mu.Lock()
	h.channels[acct.String()] = ch
	h.mu.Unlock()

	go h.deliveryLoop(ch, s.LastDelivered)

	slog.Info("delivery channel started",
		"account", acct, "session_id", s.SessionID)
}

// deliveryLoop waits for signals, reads new messages from disk, and delivers
// them via the connected session. Serialized per channel.
func (h *Hub) deliveryLoop(ch *channel, lastDelivered time.Time) {
	for {
		select {
		case <-h.ctx.Done():
			return
		case sig := <-ch.signal:
			switch sig.kind {
			case signalConnected:
				h.sendHello(ch)
				lastDelivered = h.drainAllConversations(ch, lastDelivered)
			case signalNewMessage:
				lastDelivered = h.drainConversation(ch, sig.conversation, lastDelivered)
			}
		}
	}
}

// sendHello waits for the session's SSE connection to be ready, then sends a hello.
func (h *Hub) sendHello(ch *channel) {
	h.mu.RLock()
	session := h.sessions[ch.sessionID]
	h.mu.RUnlock()

	if session == nil {
		return
	}

	// Wait for the SSE event loop to start.
	select {
	case <-session.Ready:
	case <-h.ctx.Done():
		return
	}

	hello := IncomingMsg{
		Platform:     ch.acct.Platform,
		Account:      ch.acct.Name,
		Conversation: "system",
		MsgLines:     []string{"pigeon connected to " + ch.acct.Display()},
	}
	if err := session.Send(h.ctx, hello); err != nil {
		slog.Error("failed to send hello", "session_id", ch.sessionID, "error", err)
	}
}

func (h *Hub) drainAllConversations(ch *channel, lastDelivered time.Time) time.Time {
	convs, err := store.ListConversations(ch.acct.Platform, ch.acct.NameSlug(), nil)
	if err != nil {
		slog.Error("failed to list conversations for drain",
			"account", ch.acct, "error", err)
		return lastDelivered
	}
	for _, c := range convs {
		lastDelivered = h.drainConversation(ch, c.DirName, lastDelivered)
	}
	return lastDelivered
}

func (h *Hub) drainConversation(ch *channel, conversation string, lastDelivered time.Time) time.Time {
	now := time.Now()
	since := now.Sub(lastDelivered)
	lines, err := store.ReadMessages(ch.acct.Platform, ch.acct.NameSlug(), conversation, store.ReadOpts{Since: since})
	if err != nil {
		slog.Error("failed to read messages",
			"account", ch.acct, "conversation", conversation, "error", err)
		return lastDelivered
	}

	if len(lines) == 0 {
		return lastDelivered
	}

	// Find connected session.
	h.mu.RLock()
	session := h.sessions[ch.sessionID]
	h.mu.RUnlock()

	if session == nil {
		slog.Warn("session not connected, messages pending",
			"session_id", ch.sessionID, "pending", len(lines))
		return lastDelivered
	}

	// Send all lines as a single message.
	msg := IncomingMsg{
		Platform:     ch.acct.Platform,
		Account:      ch.acct.Name,
		Conversation: conversation,
		MsgLines:     lines,
	}
	if err := session.Send(h.ctx, msg); err != nil {
		slog.Error("failed to deliver message",
			"session_id", ch.sessionID, "error", err)
		return lastDelivered
	}

	// Update cursor to now — everything up to this point has been delivered.
	if err := claude.UpdateLastDelivered(ch.acct, now); err != nil {
		slog.Error("failed to update last_delivered",
			"session_id", ch.sessionID, "error", err)
	}
	return now
}

// RegistrationError is returned when session registration fails.
type RegistrationError struct {
	SessionID string
	Reason    string
}

func (e *RegistrationError) Error() string {
	return "session " + e.SessionID + ": " + e.Reason
}
